source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '11.0'

target 'JVTransitionAnimator' do
  pod "JVTransitionAnimator", :path => "../"
end

target 'Tests' do
  pod "JVTransitionAnimator", :path => "../"
end
