source 'https://github.com/CocoaPods/Specs.git'

target 'JVTransitionAnimator', :exclusive => true do
  pod "JVTransitionAnimator", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "JVTransitionAnimator", :path => "../"

  
end
